services:
  frontend:
    build:
      context: ./frontend
    restart: always

  backend:
    build:
      context: ./backend
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:80"
    depends_on:
      - frontend
      - backend
    restart: always
